/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:CF_Name:828715:
  println("Name - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:CF_Name:828715:

public void textfield1_change2(GTextField source, GEvent event) { //_CODE_:CF_Protien:797360:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:CF_Protien:797360:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:CF_Fats:601566:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:CF_Fats:601566:

public void textfield3_change1(GTextField source, GEvent event) { //_CODE_:CF_Carbs:828846:
  println("textfield3 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:CF_Carbs:828846:

public void textfield4_change1(GTextField source, GEvent event) { //_CODE_:CF_Cost:272030:
  println("textfield4 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:CF_Cost:272030:

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:Meal:654466:
  println("Meal - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:Meal:654466:

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:D_Age:607161:
  println("slider1 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:D_Age:607161:

public void dropList1_click2(GDropList source, GEvent event) { //_CODE_:Gender:378038:
  println("Gender - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:Gender:378038:

public void slider1_change2(GSlider source, GEvent event) { //_CODE_:Exersize:707988:
  println("Exersize - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:Exersize:707988:

public void button1_click1(GButton source, GEvent event) { //_CODE_:Add_new_Food:350284:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Add_new_Food:350284:

public void button1_click2(GButton source, GEvent event) { //_CODE_:Add_New_Demo:626754:
  println("Add_New_Demo - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Add_New_Demo:626754:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  label1 = new GLabel(this, -5, 10, 120, 22);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Add Food To:");
  label1.setOpaque(false);
  label2 = new GLabel(this, 7, 78, 94, 21);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Custom Food:");
  label2.setOpaque(false);
  label3 = new GLabel(this, 38, 100, 80, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Name:");
  label3.setOpaque(false);
  CF_Name = new GTextField(this, 121, 99, 85, 22, G4P.SCROLLBARS_NONE);
  CF_Name.setOpaque(true);
  CF_Name.addEventHandler(this, "textfield1_change1");
  label4 = new GLabel(this, 38, 220, 80, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Protein");
  label4.setOpaque(false);
  label5 = new GLabel(this, 39, 190, 80, 20);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Carbs");
  label5.setOpaque(false);
  label6 = new GLabel(this, 38, 160, 80, 20);
  label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText("Fats");
  label6.setOpaque(false);
  CF_Protien = new GTextField(this, 118, 220, 87, 21, G4P.SCROLLBARS_NONE);
  CF_Protien.setOpaque(true);
  CF_Protien.addEventHandler(this, "textfield1_change2");
  CF_Fats = new GTextField(this, 119, 159, 87, 23, G4P.SCROLLBARS_NONE);
  CF_Fats.setOpaque(true);
  CF_Fats.addEventHandler(this, "textfield2_change1");
  CF_Carbs = new GTextField(this, 120, 190, 84, 20, G4P.SCROLLBARS_NONE);
  CF_Carbs.setOpaque(true);
  CF_Carbs.addEventHandler(this, "textfield3_change1");
  label7 = new GLabel(this, 36, 133, 81, 20);
  label7.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label7.setText("Macros:");
  label7.setOpaque(false);
  CF_cost = new GLabel(this, 38, 250, 80, 20);
  CF_cost.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  CF_cost.setText("Cost($)");
  CF_cost.setOpaque(false);
  CF_Cost = new GTextField(this, 121, 250, 86, 20, G4P.SCROLLBARS_NONE);
  CF_Cost.setOpaque(true);
  CF_Cost.addEventHandler(this, "textfield4_change1");
  Meal = new GDropList(this, 117, 11, 90, 100, 4, 10);
  Meal.setItems(loadStrings("list_654466"), 0);
  Meal.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  Meal.addEventHandler(this, "dropList1_click1");
  label9 = new GLabel(this, 216, 12, 108, 20);
  label9.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label9.setText("Demographic");
  label9.setOpaque(false);
  D_Age = new GSlider(this, 240, 72, 108, 48, 10.0);
  D_Age.setShowValue(true);
  D_Age.setShowLimits(true);
  D_Age.setLimits(42, 5, 80);
  D_Age.setShowTicks(true);
  D_Age.setNumberFormat(G4P.INTEGER, 0);
  D_Age.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  D_Age.setOpaque(false);
  D_Age.addEventHandler(this, "slider1_change1");
  label10 = new GLabel(this, 240, 48, 36, 24);
  label10.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label10.setText("Age:");
  label10.setOpaque(false);
  Gender = new GDropList(this, 240, 240, 90, 60, 2, 10);
  Gender.setItems(loadStrings("list_378038"), 0);
  Gender.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  Gender.addEventHandler(this, "dropList1_click2");
  Exersize = new GSlider(this, 240, 156, 108, 48, 10.0);
  Exersize.setShowValue(true);
  Exersize.setShowLimits(true);
  Exersize.setLimits(75, 0, 150);
  Exersize.setShowTicks(true);
  Exersize.setNumberFormat(G4P.INTEGER, 0);
  Exersize.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  Exersize.setOpaque(false);
  Exersize.addEventHandler(this, "slider1_change2");
  exersize = new GLabel(this, 240, 132, 120, 20);
  exersize.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  exersize.setText("Exersize Per Week:");
  exersize.setOpaque(false);
  label8 = new GLabel(this, 240, 216, 60, 20);
  label8.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label8.setText("Gender:");
  label8.setOpaque(false);
  Add_new_Food = new GButton(this, 84, 276, 96, 30);
  Add_new_Food.setText("Add New Food");
  Add_new_Food.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  Add_new_Food.addEventHandler(this, "button1_click1");
  Add_New_Demo = new GButton(this, 240, 276, 80, 30);
  Add_New_Demo.setText("Finalize");
  Add_New_Demo.addEventHandler(this, "button1_click2");
}

// Variable declarations 
// autogenerated do not edit
GLabel label1; 
GLabel label2; 
GLabel label3; 
GTextField CF_Name; 
GLabel label4; 
GLabel label5; 
GLabel label6; 
GTextField CF_Protien; 
GTextField CF_Fats; 
GTextField CF_Carbs; 
GLabel label7; 
GLabel CF_cost; 
GTextField CF_Cost; 
GDropList Meal; 
GLabel label9; 
GSlider D_Age; 
GLabel label10; 
GDropList Gender; 
GSlider Exersize; 
GLabel exersize; 
GLabel label8; 
GButton Add_new_Food; 
GButton Add_New_Demo; 
