/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:CF_Name_TB:828715:
  println("Name - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:CF_Name_TB:828715:

public void textfield1_change2(GTextField source, GEvent event) { //_CODE_:CF_Protien_TB:797360:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:CF_Protien_TB:797360:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:CF_Fats_TB:601566:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:CF_Fats_TB:601566:

public void textfield3_change1(GTextField source, GEvent event) { //_CODE_:CF_Carbs_TB:828846:
  println("textfield3 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:CF_Carbs_TB:828846:

public void textfield4_change1(GTextField source, GEvent event) { //_CODE_:CF_Cost_TB:272030:
  println("textfield4 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:CF_Cost_TB:272030:

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:Meal_Type_DP:654466:
  println("Meal - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:Meal_Type_DP:654466:

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:Age_slider:607161:
  println("slider1 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:Age_slider:607161:

public void dropList1_click2(GDropList source, GEvent event) { //_CODE_:Gender_DB:378038:
  println("Gender - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:Gender_DB:378038:

public void slider1_change2(GSlider source, GEvent event) { //_CODE_:Exersize_Slider:707988:
  println("Exersize - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:Exersize_Slider:707988:

public void button1_click1(GButton source, GEvent event) { //_CODE_:Add_Food_B:350284:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  
  
  
} //_CODE_:Add_Food_B:350284:

public void button1_click2(GButton source, GEvent event) { //_CODE_:Add_New_Demo:626754:
  println("Add_New_Demo - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Add_New_Demo:626754:

public void dropList1_click3(GDropList source, GEvent event) { //_CODE_:Preset_Meals_DB:909547:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:Preset_Meals_DB:909547:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  label1 = new GLabel(this, -5, 10, 120, 22);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Add Food To:");
  label1.setOpaque(false);
  label2 = new GLabel(this, 7, 78, 94, 21);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Custom Food:");
  label2.setOpaque(false);
  label3 = new GLabel(this, 38, 100, 80, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Name:");
  label3.setOpaque(false);
  CF_Name_TB = new GTextField(this, 121, 99, 85, 22, G4P.SCROLLBARS_NONE);
  CF_Name_TB.setOpaque(true);
  CF_Name_TB.addEventHandler(this, "textfield1_change1");
  label4 = new GLabel(this, 38, 220, 80, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Protein");
  label4.setOpaque(false);
  label5 = new GLabel(this, 39, 190, 80, 20);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Carbs");
  label5.setOpaque(false);
  label6 = new GLabel(this, 38, 160, 80, 20);
  label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText("Fats");
  label6.setOpaque(false);
  CF_Protien_TB = new GTextField(this, 118, 220, 87, 21, G4P.SCROLLBARS_NONE);
  CF_Protien_TB.setOpaque(true);
  CF_Protien_TB.addEventHandler(this, "textfield1_change2");
  CF_Fats_TB = new GTextField(this, 119, 159, 87, 23, G4P.SCROLLBARS_NONE);
  CF_Fats_TB.setOpaque(true);
  CF_Fats_TB.addEventHandler(this, "textfield2_change1");
  CF_Carbs_TB = new GTextField(this, 120, 190, 84, 20, G4P.SCROLLBARS_NONE);
  CF_Carbs_TB.setOpaque(true);
  CF_Carbs_TB.addEventHandler(this, "textfield3_change1");
  label7 = new GLabel(this, 36, 133, 81, 20);
  label7.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label7.setText("Macros:");
  label7.setOpaque(false);
  CF_cost = new GLabel(this, 38, 250, 80, 20);
  CF_cost.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  CF_cost.setText("Cost($)");
  CF_cost.setOpaque(false);
  CF_Cost_TB = new GTextField(this, 121, 250, 86, 20, G4P.SCROLLBARS_NONE);
  CF_Cost_TB.setOpaque(true);
  CF_Cost_TB.addEventHandler(this, "textfield4_change1");
  Meal_Type_DP = new GDropList(this, 117, 11, 90, 100, 4, 10);
  Meal_Type_DP.setItems(loadStrings("list_654466"), 0);
  Meal_Type_DP.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  Meal_Type_DP.addEventHandler(this, "dropList1_click1");
  label9 = new GLabel(this, 216, 12, 108, 20);
  label9.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label9.setText("Demographic");
  label9.setOpaque(false);
  Age_slider = new GSlider(this, 240, 72, 108, 48, 10.0);
  Age_slider.setShowValue(true);
  Age_slider.setShowLimits(true);
  Age_slider.setLimits(42, 5, 80);
  Age_slider.setShowTicks(true);
  Age_slider.setNumberFormat(G4P.INTEGER, 0);
  Age_slider.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  Age_slider.setOpaque(false);
  Age_slider.addEventHandler(this, "slider1_change1");
  label10 = new GLabel(this, 240, 60, 36, 24);
  label10.setText("Age:");
  label10.setOpaque(false);
  Gender_DB = new GDropList(this, 240, 240, 90, 60, 2, 10);
  Gender_DB.setItems(loadStrings("list_378038"), 0);
  Gender_DB.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  Gender_DB.addEventHandler(this, "dropList1_click2");
  Exersize_Slider = new GSlider(this, 240, 156, 108, 48, 10.0);
  Exersize_Slider.setShowValue(true);
  Exersize_Slider.setShowLimits(true);
  Exersize_Slider.setLimits(75, 0, 150);
  Exersize_Slider.setShowTicks(true);
  Exersize_Slider.setNumberFormat(G4P.INTEGER, 0);
  Exersize_Slider.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  Exersize_Slider.setOpaque(false);
  Exersize_Slider.addEventHandler(this, "slider1_change2");
  exersize = new GLabel(this, 240, 132, 120, 20);
  exersize.setText("Exersize Per Week:");
  exersize.setOpaque(false);
  label8 = new GLabel(this, 240, 216, 60, 20);
  label8.setText("Gender:");
  label8.setOpaque(false);
  Add_Food_B = new GButton(this, 84, 276, 96, 30);
  Add_Food_B.setText("Add New Food");
  Add_Food_B.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  Add_Food_B.addEventHandler(this, "button1_click1");
  Add_New_Demo = new GButton(this, 240, 276, 80, 30);
  Add_New_Demo.setText("Finalize");
  Add_New_Demo.addEventHandler(this, "button1_click2");
  Preset_Meals = new GLabel(this, -1, 35, 118, 20);
  Preset_Meals.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Preset_Meals.setText("Preset Meals");
  Preset_Meals.setOpaque(false);
  Preset_Meals_DB = new GDropList(this, 117, 35, 90, 80, 3, 10);
  Preset_Meals_DB.setItems(loadStrings("list_909547"), 0);
  Preset_Meals_DB.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  Preset_Meals_DB.addEventHandler(this, "dropList1_click3");
}

// Variable declarations 
// autogenerated do not edit
GLabel label1; 
GLabel label2; 
GLabel label3; 
GTextField CF_Name_TB; 
GLabel label4; 
GLabel label5; 
GLabel label6; 
GTextField CF_Protien_TB; 
GTextField CF_Fats_TB; 
GTextField CF_Carbs_TB; 
GLabel label7; 
GLabel CF_cost; 
GTextField CF_Cost_TB; 
GDropList Meal_Type_DP; 
GLabel label9; 
GSlider Age_slider; 
GLabel label10; 
GDropList Gender_DB; 
GSlider Exersize_Slider; 
GLabel exersize; 
GLabel label8; 
GButton Add_Food_B; 
GButton Add_New_Demo; 
GLabel Preset_Meals; 
GDropList Preset_Meals_DB; 
