/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:CF_Name_TB:828715:
  println("Name - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:CF_Name_TB:828715:

public void textfield1_change2(GTextField source, GEvent event) { //_CODE_:CF_Protien_TB:797360:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:CF_Protien_TB:797360:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:CF_Fats_TB:601566:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:CF_Fats_TB:601566:

public void textfield3_change1(GTextField source, GEvent event) { //_CODE_:CF_Carbs_TB:828846:
  println("textfield3 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:CF_Carbs_TB:828846:

public void textfield4_change1(GTextField source, GEvent event) { //_CODE_:CF_Cost_TB:272030:
  println("textfield4 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:CF_Cost_TB:272030:

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:Meal_Type_DP:654466:
  println("Meal - GDropList >> GEvent." + event + " @ " + millis());
  
 
  //add to the texbox


  
  

  
  } //_CODE_:Meal_Type_DP:654466:

public void Add_Food_b(GButton source, GEvent event) { //_CODE_:Add_Food_B:350284:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  
 
  //.getText is a medthod from G4P libary that gets the text text from the text box
  
  String foodName = CF_Name_TB.getText();        // Gets the name they tybed
  float protein = Float.parseFloat(CF_Protien_TB.getText());  // Gets protein value
  float carbs = Float.parseFloat(CF_Carbs_TB.getText());      // Gets carbs value
  float fats = Float.parseFloat(CF_Fats_TB.getText());        // Gets fats value
  float cost = Float.parseFloat(CF_Cost_TB.getText());        // Gets cost value

  //make a new FoodItem object with the values form the textbox
  FoodItem newFood = new FoodItem(foodName, protein, carbs, fats, cost);

  //add the new food object to the food manager's custom food list
  FM.addFood(newFood); 

  
  Preset_Meals_DB.setItems(FM.getNames(), FM.getNames().length - 1);

  
  //clear is another method from G4P that clears the text box
  CF_Name_TB.setText("");
  CF_Protien_TB.setText("");
  CF_Carbs_TB.setText("");
  CF_Fats_TB.setText("");
  CF_Cost_TB.setText("");
  
  FM.allFood();
  
  
  
} //_CODE_:Add_Food_B:350284:

public void dropList1_click3(GDropList source, GEvent event) { //_CODE_:Preset_Meals_DB:909547:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:Preset_Meals_DB:909547:

public void slider1_change3(GSlider source, GEvent event) { //_CODE_:Time_Slide:814781:
  println("slider1 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:Time_Slide:814781:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:981941:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  
  //to add the food to the meal type
  
  //we need to get the selected food from the dropdown
  
  //finds the name
  String foodName = Preset_Meals_DB.getSelectedText();
  
  //find the foodItem using the name
  FoodItem selectedFood = FM.getFoodByName(foodName);
  
  //TO select which meal type we are addint it to breakfat, dinner, lunch, snack
  String mealType = Meal_Type_DP.getSelectedText();
  
  //add it to their arrays:
  
  if(mealType.equals("Breakfast")) {
    FM.breakfastFoods.add(selectedFood);
  } else if(mealType.equals("Lunch")) {
    FM.lunchFoods.add(selectedFood);
  } else if(mealType.equals("Dinner")) { 
    FM.dinnerFoods.add(selectedFood);
  } else if(mealType.equals("Snack")) {
    FM.snackFoods.add(selectedFood);
  }
  
  
  
} //_CODE_:button1:981941:

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:imgButton1:324482:
  println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton1:324482:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.CYAN_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  label1 = new GLabel(this, 769, 88, 120, 22);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Add Food To:");
  label1.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label1.setOpaque(false);
  label2 = new GLabel(this, 522, 4, 107, 34);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Custom Food:");
  label2.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label2.setOpaque(false);
  label3 = new GLabel(this, 527, 51, 80, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Name:");
  label3.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label3.setOpaque(false);
  CF_Name_TB = new GTextField(this, 619, 50, 85, 22, G4P.SCROLLBARS_NONE);
  CF_Name_TB.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  CF_Name_TB.setOpaque(true);
  CF_Name_TB.addEventHandler(this, "textfield1_change1");
  label4 = new GLabel(this, 527, 193, 80, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Protein");
  label4.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label4.setOpaque(false);
  label5 = new GLabel(this, 529, 157, 80, 20);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Carbs");
  label5.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label5.setOpaque(false);
  label6 = new GLabel(this, 528, 120, 80, 20);
  label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText("Fats");
  label6.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label6.setOpaque(false);
  CF_Protien_TB = new GTextField(this, 621, 193, 87, 21, G4P.SCROLLBARS_NONE);
  CF_Protien_TB.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  CF_Protien_TB.setOpaque(true);
  CF_Protien_TB.addEventHandler(this, "textfield1_change2");
  CF_Fats_TB = new GTextField(this, 619, 117, 87, 23, G4P.SCROLLBARS_NONE);
  CF_Fats_TB.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  CF_Fats_TB.setOpaque(true);
  CF_Fats_TB.addEventHandler(this, "textfield2_change1");
  CF_Carbs_TB = new GTextField(this, 621, 157, 84, 20, G4P.SCROLLBARS_NONE);
  CF_Carbs_TB.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  CF_Carbs_TB.setOpaque(true);
  CF_Carbs_TB.addEventHandler(this, "textfield3_change1");
  label7 = new GLabel(this, 527, 86, 81, 20);
  label7.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label7.setText("Macros:");
  label7.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label7.setOpaque(false);
  CF_cost = new GLabel(this, 527, 229, 80, 20);
  CF_cost.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  CF_cost.setText("Cost($)");
  CF_cost.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  CF_cost.setOpaque(false);
  CF_Cost_TB = new GTextField(this, 621, 226, 86, 20, G4P.SCROLLBARS_NONE);
  CF_Cost_TB.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  CF_Cost_TB.setOpaque(true);
  CF_Cost_TB.addEventHandler(this, "textfield4_change1");
  Meal_Type_DP = new GDropList(this, 894, 171, 90, 100, 4, 10);
  Meal_Type_DP.setItems(loadStrings("list_654466"), 0);
  Meal_Type_DP.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  Meal_Type_DP.addEventHandler(this, "dropList1_click1");
  Add_Food_B = new GButton(this, 565, 265, 96, 30);
  Add_Food_B.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  Add_Food_B.setText("Add New Food");
  Add_Food_B.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  Add_Food_B.addEventHandler(this, "Add_Food_b");
  Preset_Meals = new GLabel(this, 773, 170, 118, 20);
  Preset_Meals.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Preset_Meals.setText("Preset Meals");
  Preset_Meals.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  Preset_Meals.setOpaque(false);
  Preset_Meals_DB = new GDropList(this, 893, 89, 90, 80, 3, 10);
  Preset_Meals_DB.setItems(loadStrings("list_909547"), 0);
  Preset_Meals_DB.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  Preset_Meals_DB.addEventHandler(this, "dropList1_click3");
  TIme = new GLabel(this, 778, 12, 94, 36);
  TIme.setText("Time Control");
  TIme.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  TIme.setOpaque(false);
  Time_Slide = new GSlider(this, 882, 32, 106, 41, 10.0);
  Time_Slide.setShowValue(true);
  Time_Slide.setLimits(7, 0, 14);
  Time_Slide.setNumberFormat(G4P.INTEGER, 0);
  Time_Slide.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  Time_Slide.setOpaque(false);
  Time_Slide.addEventHandler(this, "slider1_change3");
  Time_Slider_Lable = new GLabel(this, 883, 6, 80, 20);
  Time_Slider_Lable.setText("Time In Days");
  Time_Slider_Lable.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  Time_Slider_Lable.setOpaque(false);
  button1 = new GButton(this, 795, 233, 80, 30);
  button1.setText("Add Food To Table ");
  button1.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  button1.addEventHandler(this, "button1_click1");
  imgButton1 = new GImageButton(this, 356, 218, 100, 60, new String[] { "", "", "" } );
  imgButton1.addEventHandler(this, "imgButton1_click1");
}

// Variable declarations 
// autogenerated do not edit
GLabel label1; 
GLabel label2; 
GLabel label3; 
GTextField CF_Name_TB; 
GLabel label4; 
GLabel label5; 
GLabel label6; 
GTextField CF_Protien_TB; 
GTextField CF_Fats_TB; 
GTextField CF_Carbs_TB; 
GLabel label7; 
GLabel CF_cost; 
GTextField CF_Cost_TB; 
GDropList Meal_Type_DP; 
GButton Add_Food_B; 
GLabel Preset_Meals; 
GDropList Preset_Meals_DB; 
GLabel TIme; 
GSlider Time_Slide; 
GLabel Time_Slider_Lable; 
GButton button1; 
GImageButton imgButton1; 
